#!/bin/bash

set -e -x

cargo fmt -- --check
cargo clippy $@ --all-targets
cargo clippy $@ --all-targets --features=dump-graphs
cargo clippy $@ --all-targets --features=testing
cargo clippy $@ --all-targets --features=testing,malice-detection
cargo clippy $@ --all-targets --features=dump-graphs,testing
cargo clippy $@ --all-targets --features=dump-graphs,testing,malice-detection
cargo clippy $@ --all-targets --features=mock
cargo clippy $@ --all-targets --features=mock,dump-graphs
cargo clippy $@ --all-targets --features=mock,dump-graphs,malice-detection
cargo clippy $@ --manifest-path=dot_gen/Cargo.toml
